#!/bin/env bash
if [ $# -eq 0 ]; then
    CMD="sh -l"
else
    CMD="$@"
fi

if [ -z "$ECHO" ]; then
    echo_cmd=echo
fi

exec $echo_cmd env \
  -i \
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
  TERM=screen-256color \
  COLORTERM=truecolor \
  PROOT_L2S_DIR=/data/data/com.termux/files/usr/var/lib/proot-distro/containers/alpine/rootfs/.l2s \
  /data/data/com.termux/files/usr/bin/proot \
  --kill-on-exit \
  --link2symlink \
  -L \
  --change-id=0:0 \
  --rootfs=/data/data/com.termux/files/usr/var/lib/proot-distro/containers/alpine/rootfs \
  --cwd=/root \
  --bind=/dev \
  --bind=/proc \
  --bind=/sys \
  $PROOT_FLAGS \
  /bin/sh \
  -c "$CMD"
